return {
	CrystalGuardian = {
		DisplayName = "Crystal Guardian",
		Health = 2500,
		Level = 15,
		XP = 1800,
		Money = 1200,
		Respawn = 90,
		AggroRange = 65,
		AttackRange = 9,
		AttackDamage = 28,
		AttackCooldown = 1.4,
		AbilityCooldown = 6,
		AbilityRadius = 14,
		AbilityDamage = 45,
		Telegraph = {
			Cooldown = 5.5,
			Windup = 0.8,
			Radius = 8,
			Damage = 32,
			TargetRange = 70,
		},
		Drop = "GuardianCore",
	},
}
